pipeline {
    agent any
    stages {
        
        stage('preparation') {
            steps {
                git 'https://github.com/MohamedAdelTaha/Simple_Nodejs_App.git'
            }
        }
        stage('Build') {
            steps {
                sh 'docker build . -t mohamedadeltaha/simple-node-app:v5.0'
            }
        }
        stage('artifact') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh 'docker login -u ${USERNAME} -p ${PASSWORD}'
                    sh 'docker push mohamedadeltaha/simple-node-app:v5.0'
                }
            }
        }
        stage('App-Deploy') {
            steps {
                sh 'kubectl apply -f /node-app-dep.yml --namespace prod'
            }
        }
        stage('Service-Deploy') {
            steps {
                sh 'kubectl apply -f /node-svc.yml --namespace prod'
            }
        }
    }
}